# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

# default: &default
#   adapter: postgresql
#   encoding: unicode
#   # For details on connection pooling, see rails configuration guide
#   # http://guides.rubyonrails.org/configuring.html#database-pooling
#   pool: 5
#   username: blhniqgohxgzfi
#   password: _kP8fYLBjJzQLRBNflQuCbh33n
#   host: ec2-54-83-27-147.compute-1.amazonaws.com
#   port: 5432
#   database: d615277ttnh1bc

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  username: helpers4cmu
  password: rails
  host: localhost
  port: 
  database: helpers4cmu

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

