# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

# development:
#   adapter: postgresql
#   database: helpers4cmu
#   pool: 5
#   username: helpers4cmu
#   password: rails
#   host: localhost
#   port: 

# test:
#   adapter: postgresql
#   database: helpers4cmu
#   pool: 5
#   username: helpers4cmu
#   password: rails
#   host: localhost
#   port: 

# production:
#   adapter: postgresql
#   database: helpers4cmu
#   pool: 5
#   username: helpers4cmu
#   password: rails
#   host: localhost
#   port: 

development:
  adapter: postgresql
  database: d615277ttnh1bc
  pool: 5
  username: blhniqgohxgzfi
  password: _kP8fYLBjJzQLRBNflQuCbh33n
  host: ec2-54-83-27-147.compute-1.amazonaws.com
  port: 5432

test:
  adapter: postgresql
  database: d615277ttnh1bc
  pool: 5
  username: blhniqgohxgzfi
  password: _kP8fYLBjJzQLRBNflQuCbh33n
  host: ec2-54-83-27-147.compute-1.amazonaws.com
  port: 5432

production:
  adapter: postgresql
  database: d615277ttnh1bc
  pool: 5
  username: blhniqgohxgzfi
  password: _kP8fYLBjJzQLRBNflQuCbh33n
  host: ec2-54-83-27-147.compute-1.amazonaws.com
  port: 5432